import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
   
  },
  gridContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    pointerEvents: 'none',
  },
  
  gridLine: {
    position: 'absolute',
    backgroundColor: Platform.OS === 'android' ? 'rgba(59, 130, 246, 0.03)' : 'rgba(59, 130, 246, 0.08)', // Lower opacity on Android
  },
  loadingContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 60,
    zIndex: 1,
  },
  titleLogo: {
    width: width * 0.8,
    maxWidth: 400,
    height: 200,
    marginBottom: 40,
  },
  gooseLogoContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  gooseLogo: {
    width: 300,
    height: 300,
  },
  startButtonContainer: {
    position: 'absolute',
    bottom: 60,
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 2,
  },
  startButton: {
    backgroundColor: '#F97316',
    paddingVertical: 16,
    paddingHorizontal: 60,
    borderRadius: 30,
    shadowColor: '#F97316',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    elevation: 8,
  },
  startButtonText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: 'bold',
    letterSpacing: 2,
  },
  content: {
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#2563EB',
    marginBottom: 12,
    textShadowColor: 'rgba(30, 111, 227, 0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
  },
  subtitle: {
    fontSize: 18,
    color: '#FFFFFF',
    opacity: 0.9,
  },
  keyboardAvoidingView: {
    flex: 1,
    width: '100%',
  },
  loginScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingVertical: 40,
  },
  loginContent: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 40,
    zIndex: 1,
  },
  loginTitleLogo: {
    width: width * 0.8,
    maxWidth: 400,
    height: 150,
    marginBottom: 30,
  },
  loginForm: {
    width: width * 0.85,
    maxWidth: 400,
  },
  inputContainer: {
    marginBottom: 24,
    width: '100%',
  },
  inputLabel: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
  },
  input: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(37, 99, 235, 0.2)',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: '#FFFFFF',
    fontSize: 16,
    height: 50,
    width: '100%',
    flexShrink: 0,
    minWidth: '100%',
  },
  loginGooseLogo: {
    width: 200,
    height: 200,
    marginBottom: 40,
  },
  homeContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  logoutButton: {
    position: 'absolute',
    top: 60,
    right: 20,
    backgroundColor: '#F97316',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 20,
    zIndex: 2,
    shadowColor: '#F97316',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 5,
  },
  logoutButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  loginButton: {
    backgroundColor: '#F97316',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 20,
    shadowColor: '#F97316',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    elevation: 8,
  },
  loginButtonDisabled: {
    opacity: 0.6,
  },
  loginButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
    letterSpacing: 1.5,
  },
 
  screenContentContainer: {
    padding: 20,
    paddingBottom: 120,
    paddingTop: 20,
  },
  screenContentContainerWithTopBar: {
    padding: 20,
    paddingBottom: 120,
    paddingTop: 10,
  },
  screenTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 20,
    textAlign: 'center',
  },
  centeredText: {
    fontSize: 16,
    color: '#FFFFFF',
    textAlign: 'center',
    marginTop: 20,
    opacity: 0.7,
  },
  defaultProfilePic: {
    backgroundColor: '#2563EB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  defaultProfilePicText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  profileHeaderCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 12,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: 'rgba(37, 99, 235, 0.2)',
  },
  profileHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  profileHeaderText: {
    marginLeft: 16,
    flex: 1,
  },
  profileHeaderName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  weeklyDistanceContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  weeklyDistanceLabel: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.7)',
    marginRight: 8,
  },
  weeklyDistanceValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#F97316',
  },
  workoutCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 12,
    padding: 15,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: 'rgba(37, 99, 235, 0.2)',
  },
  workoutTopSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  workoutHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  workoutHeaderText: {
    marginLeft: 12,
    flex: 1,
  },
  workoutAthleteName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  workoutDateInfo: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.7)',
  },
  activityBadge: {
    backgroundColor: '#F97316',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    alignSelf: 'flex-start',
  },
  activityBadgeText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  workoutTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  workoutStats: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 8,
    paddingVertical: 8,
  },
  workoutStatItem: {
    alignItems: 'center',
  },
  workoutStatLabel: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.7)',
    marginBottom: 4,
  },
  workoutStatValue: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  mapContainer: {
    height: 250,
    borderRadius: 8,
    overflow: 'hidden',
    marginTop: 5,
  },
  workoutActions: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.1)',
  },
  wingButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
  },
  wingButtonLiked: {
    // Additional styling when liked if needed
  },
  gooseLikeContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  gooseLikeContainerLiked: {
    backgroundColor: 'rgba(249, 115, 22, 0.2)',
    borderRadius: 20,
    padding: 4,
    borderWidth: 2,
    borderColor: '#F97316',
  },
  gooseLikeIcon: {
    width: 28,
    height: 28,
    opacity: 0.6,
  },
  gooseLikeIconLiked: {
    width: 32,
    height: 32,
    opacity: 1,
  },
  actionSeparator: {
    width: 1,
    height: 30,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  commentButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
  },
  map: {
    flex: 1,
  },
  mapPlaceholder: {
    flex: 1,
    backgroundColor: 'rgba(17, 71, 182, 0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    minHeight: 200,
  },
  mapPlaceholderText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 5,
  },
  mapPlaceholderSubtext: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.7)',
  },
  plannedWorkoutCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 12,
    padding: 15,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: 'rgba(37, 99, 235, 0.2)',
  },
  plannedWorkoutTopSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  plannedWorkoutHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  plannedWorkoutHeaderText: {
    marginLeft: 12,
    flex: 1,
  },
  plannedWorkoutCoachName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  plannedWorkoutDateInfo: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.7)',
  },
  plannedWorkoutBadge: {
    backgroundColor: '#2563EB',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    alignSelf: 'flex-start',
  },
  plannedWorkoutBadgeText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  plannedWorkoutTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 12,
  },
  plannedWorkoutDescription: {
    fontSize: 14,
    color: '#FFFFFF',
    lineHeight: 20,
  },
  plannedWorkoutActions: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.1)',
  },
  plannedWingButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
  },
  plannedWingButtonLiked: {
    // Additional styling when liked if needed
  },
  plannedGooseLikeContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  plannedGooseLikeContainerLiked: {
    backgroundColor: 'rgba(249, 115, 22, 0.2)',
    borderRadius: 20,
    padding: 4,
    borderWidth: 2,
    borderColor: '#F97316',
  },
  plannedGooseLikeIcon: {
    width: 28,
    height: 28,
    opacity: 0.6,
  },
  plannedGooseLikeIconLiked: {
    width: 32,
    height: 32,
    opacity: 1,
  },
  plannedActionSeparator: {
    width: 1,
    height: 30,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  plannedCommentButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
  },
  sleepDataContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 12,
    padding: 20,
    marginTop: 20,
    borderWidth: 1,
    borderColor: 'rgba(37, 99, 235, 0.2)',
  },
  sleepDataTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 20,
    textAlign: 'center',
  },
  pieChartContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    position: 'relative',
  },
  pieChartCenter: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pieChartCenterValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  pieChartCenterLabel: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.7)',
  },
  sleepLegend: {
    marginTop: 10,
  },
  sleepLegendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    width: '100%',
  },
  sleepColorBox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    marginRight: 10,
  },
  sleepLegendText: {
    fontSize: 14,
    color: '#FFFFFF',
  },
  myAthleteCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 12,
    padding: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(37, 99, 235, 0.2)',
    width: (width - 50) / 2,
  },
  myAthleteName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginTop: 10,
    marginBottom: 10,
  },
  viewAthleteButton: {
    backgroundColor: '#F97316',
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
  viewAthleteButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  athletesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 10,
    paddingHorizontal: 20,
  },
  flockCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 12,
    padding: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(37, 99, 235, 0.2)',
    width: (width - 50) / 2,
  },
  flockPic: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#1E3A8A',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  flockPicText: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  flockName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 10,
  },
  addWorkoutButton: {
    backgroundColor: '#F97316',
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
  addWorkoutButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  flockGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 10,
    paddingHorizontal: 20,
  },
  settingsProfileSection: {
    alignItems: 'center',
    marginTop: 20,
  },
  settingsUserName: {
    fontSize: 20,
    fontWeight: '600',
    color: '#FFFFFF',
    marginTop: 15,
    marginBottom: 10,
  },
  settingsButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 12,
    marginTop: 15,
    width: '100%',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(37, 99, 235, 0.2)',
  },
  logoutButtonSettings: {
    backgroundColor: '#F97316',
    marginTop: 30,
  },
  settingsButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  searchInput: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(37, 99, 235, 0.2)',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: '#FFFFFF',
    fontSize: 16,
    marginBottom: 20,
  },
  profileHeader: {
    marginBottom: 30,
  },
  profileTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  profileName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginLeft: 20,
    flex: 1,
  },
  profileStats: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    paddingHorizontal: 20,
  },
  profileStatItem: {
    alignItems: 'center',
  },
  profileStatNumber: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2563EB',
  },
  profileStatLabel: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.8)',
    marginTop: 5,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginTop: 20,
    marginBottom: 15,
  },
  instagramProfileContainer: {
    paddingBottom: 120,
  },
  instagramBackButton: {
    position: 'absolute',
    top: 10,
    left: 20,
    zIndex: 100,
    padding: 8,
    paddingHorizontal: 10,
    borderRadius: 18,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  refreshButton: {
    position: 'absolute',
    top: 100,
    right: 20,
    zIndex: 101,
    backgroundColor: '#F97316',
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#F97316',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    elevation: 8,
  },
  instagramProfileHeader: {
    paddingHorizontal: 15,
    paddingTop: 10,
    paddingBottom: 15,
  },
  instagramProfileTop: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  instagramStatsRow: {
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'space-around',
    marginLeft: 20,
  },
  instagramStatItem: {
    alignItems: 'center',
  },
  instagramStatNumber: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  instagramStatLabel: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.7)',
    marginTop: 2,
  },
  instagramBioSection: {
    marginTop: 8,
  },
  instagramUsername: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  instagramBio: {
    fontSize: 14,
    color: '#FFFFFF',
    lineHeight: 20,
    opacity: 0.9,
  },
  instagramTabBar: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    marginTop: 10,
  },
  instagramTab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
  },
  instagramTabActive: {
    borderBottomWidth: 2,
    borderBottomColor: '#FFFFFF',
  },
  instagramTabDivider: {
    width: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  instagramGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 2,
  },
  instagramGridItem: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    margin: 0.5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  instagramGridItemContent: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  instagramGridItemText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 4,
  },
  instagramGridItemEmpty: {
    backgroundColor: 'transparent',
    borderWidth: 0,
  },
  instagramListContainer: {
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  instagramSectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginTop: 20,
    marginBottom: 15,
  },
  datePickerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    padding: 15,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(37, 99, 235, 0.2)',
  },
  datePickerLabel: {
    fontSize: 16,
    color: '#FFFFFF',
    marginRight: 15,
    fontWeight: '600',
  },
  dateInput: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(37, 99, 235, 0.2)',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    justifyContent: 'center',
  },
  dateInputText: {
    color: '#FFFFFF',
    fontSize: 16,
  },
  errorContainer: {
    flex: 1,
    padding: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#F97316',
    marginBottom: 20,
  },
  errorText: {
    fontSize: 16,
    color: '#FFFFFF',
    marginBottom: 10,
    textAlign: 'center',
  },
  errorMessage: {
    fontSize: 14,
    color: '#FFFFFF',
    marginBottom: 20,
    textAlign: 'center',
    opacity: 0.8,
  },
  errorStack: {
    maxHeight: 200,
    width: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: 8,
    padding: 10,
    marginTop: 10,
  },
  errorStackTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#F97316',
    marginBottom: 5,
  },
  errorStackText: {
    fontSize: 10,
    color: '#FFFFFF',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  backButton: {
    alignSelf: 'flex-start',
    marginBottom: 20,
    paddingVertical: 10,
    paddingHorizontal: 15,
  },
  backButtonText: {
    color: '#2563EB',
    fontSize: 16,
    fontWeight: '600',
  },
  userListItem: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    padding: 15,
    borderRadius: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(37, 99, 235, 0.2)',
    flexDirection: 'row',
    alignItems: 'center',
  },
  userNameText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 15,
  },
});

export { width, height };

